### PR TITLE
Update telos gh workflow

### PR DESCRIPTION
**Pull request by JustinCast**
### What does this PR do?

- related to #401 

### Steps to test
Does not apply

#### CheckList

- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

### CODE REVIEW

**Comment by JustinCast** [comment]
@kuronosec @xavier506 please leave a review on this 🙏🏼

**Comment by JustinCast** [comment]
@xavier506 @kuronosec

**Review by kuronosec — CHANGES_REQUESTED** [review]
I have left one comment. please take a look of how other workflows configure the kubernetes environment and deploy the scripts.

**Review by kuronosec — APPROVED** [review]
LGTM

**Pull request merged**
