### PR TITLE
Alignment issues

### LINKED ISSUE #655: Homepage element alignment
Let's fix the alignment for the following elements. Thanks.

You can refer to this design: https://zpl.io/VDmGvL3

As seen on iphone SE (Chrome).
File

### LINKED ISSUE #657: Alignment issues
There's a series of alignment issues on the mobile version of the dashboard. Please take a look at the comments on this Zeplin frame: https://zpl.io/aNYJDgQ

### PR DESCRIPTION
**Pull request by AngeloCG97**
## Homepage element alignment

- Resolve #657
- Resolve #655

### What does this PR do?

- Fix align dashboard header
- Align networks images and texts on lading page

### CODE REVIEW

**Review by tetogomez — APPROVED** [review]
LGTM

**Comment by AngeloCG97** [comment]
Fix #655 

image
image

**Review by tetogomez — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM

**Pull request merged**
